### ISSUE TITLE
ACF Pro compatibility

### ISSUE THREAD

**Issue by bogdancss** [jabranr/nullify-empty-fields-for-acf#1]
We've got ACF Pro plugin installed and are getting the `This plugin only works with Advanced Custom Fields (ACF). Please install and activate ACF before using this plugin.` error.

Is it possible to make this compatible with both versions of the plugin?

**Comment by jabranr** [comment]
@bogdancss Thank you for reporting. I can certainly look into this.

**Comment by jabranr** [comment]
@bogdancss this should be fixed now with v1.1.0. Just install it from WP plugins or update the plugin if you have already installed it.

**Comment by bogdancss** [comment]
@jabranr I can confirm the plugin activates as expected. thank you!
