### ISSUE TITLE
Is there a way to revert the changes made by the plugin?

### ISSUE THREAD

**Issue by domvo** [jabranr/nullify-empty-fields-for-acf#9]
Let's assume I now have a better GraphQL querying process and I don't need this fix anymore, is there an elegant way to revert all the nulls to empty strings?

**Comment by jabranr** [comment]
@domvo this plugin does not change the actual values but it is only a filter to mutate empty fields to `null` before passing into the API response. If you disable/uninstall the plugin then you should again start getting the default empty value – that is believe to be a boolean `false`. Does that answer your question?
